export { transformStaticImports } from './staticImportToDynamic'
export { createDynamicImportsVisitor } from './resolveDynamicImport'
export { createImportMetaVisitor, type ReplaceImportMetaOptions } from './replaceImportMeta'
export { createLookbehindVisitor } from './removeLookbehind'
export { transformExports, type RemoveExportOptions } from './removeExport'
export { createStaticBlocksVisitor } from './transformStaticBlock'
export { createStaticClassFieldsVisitor } from './transformStaticClassField'
export { createInstanceClassFieldsVisitor } from './transformInstanceClassField'
export { createLogicalAssignmentVisitor } from './transformLogicalAssignment'
export { createBigIntVisitor } from './transformBigInt'
export { createPrivateFieldsVisitor } from './transformPrivateFields'
export { transformWrapAsyncIIFE, type WrapAsyncIIFEOptions } from './wrapAsyncIIFE'
export { mergeVisitors } from './mergeVisitors'
